version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-mistral
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Optional: Pull the Mistral model on startup
  mistral-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    entrypoint: ["ollama", "pull", "mistral"]
    restart: "no"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
